### ISSUE TITLE
error open raven with kali linux

### ISSUE THREAD

**Issue by bxchipID** [0x09AL/raven#10]
root@:~/Destop/raven# python raven.py
Traceback (most recent call last):
  File "raven.py", line 2, in <module>
    from modules import requester
  File "/root/Destop/raven/modules/requester.py", line 1, in <module>
    from selenium import webdriver
ImportError: No module named selenium

**Comment by 0x09AL** [comment]
Did you install selenium ?

**Comment by bxchipID** [comment]
not yet, oke thanks works sir

**Comment by 0x09AL** [comment]
Ok cool.
