### ISSUE TITLE
No report

### ISSUE THREAD

**Issue by psychomad** [0x09AL/raven#11]
Hello, first of all nice tool, thanks
Second thing, i got this error when the tool ask me which format i want:

#> Enter format number: 1
╒════════╤════════════╤═══════════╤══════════╕
│ Name   │ Position   │ Company   │ E-mail   │
╞════════╪════════════╪═══════════╪══════════╡
╘════════╧════════════╧═══════════╧══════════╛
[+] Saving output to output/xxxxxxx.com-1504800726.csv
Traceback (most recent call last):
  File "raven.py", line 184, in <module>
    RequesterObject.kill()
  File "/home/doctorplague/raven/modules/requester.py", line 75, in kill
    self.driver.quit()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 181, in quit
    RemoteWebDriver.quit(self)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 551, in quit
    self.execute(Command.QUIT)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: quit

I check if Selenium (pip and python-selenium) are installed and upgraded and everything is fine... any suggestion?

**Comment by 0x09AL** [comment]
Hi ,
I think this is an issue with the version of firefox in Kali Linux. Try to update it and let me know.

**Comment by psychomad** [comment]
Hi
I update firefox, i try to install another version and update it. no luck

**Comment by d3cod3r** [comment]
To fix this issue edit the file /usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py and change the self.execute(Command.QUIT) statement with the following:

self.execute(Command.CLOSE)

This fixed the error for me. Hope it can help

**Comment by lorenzoromani1983** [comment]
I get a "list index out of range" error for every employee scraped from Google. What to do next?

tnx!

**Comment by 0x09AL** [comment]
You should clear the cache and cookies of firefox. The error can be caused by different things but most probably Linkedin is showing the old template (Which is not implemented in this version.)

**Comment by psychomad** [comment]
thnx a lot
