### ISSUE TITLE
LinkedIn Recruiter Account

### ISSUE THREAD

**Issue by Green-Wolf** [0x09AL/raven#12]
Hi sorry to make an issue for this but i have a question about the tool. 

Does it support recruiter accounts? As to me it seems the only limitation is that its based off my personal linkedin accounts network. Does it work even better with recruiter accounts?

**Comment by 0x09AL** [comment]
Hi,
As this doesn't use the linkedin search feature having a recruiter profile will not make any difference.
Normally every account that can view a profile can work since the URLs are extracted from search engines.
