### ISSUE TITLE
Failed Login

### ISSUE THREAD

**Issue by jimmybarber** [0x09AL/raven#14]
Hi, 

Great tool but I am having some difficulty with the linkedin authentication I keep getting a Login Failed message, I have updated firefox and reinstalled the tool, I have confirmed the creds and they work fine from a browser session. Looking in the Geko driver log I can see the following

1505893712514	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.linkedin.com/uas/login"
1505893712547	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483655"
1505893712680	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.linkedin.com/uas/login"
1505893712682	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.linkedin.com/uas/login"
1505893712701	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.linkedin.com/uas/login"
1505893713397	Marionette	DEBUG	Received DOM event "beforeunload" for "https://www.linkedin.com/uas/login"
1505893714406	Marionette	DEBUG	Received DOM event "pagehide" for "https://www.linkedin.com/uas/login"
1505893714411	Marionette	DEBUG	Received DOM event "unload" for "https://www.linkedin.com/uas/login"
*************************
A coding exception was thrown and uncaught in a Task.

Full message: TypeError: NetworkError when attempting to fetch resource.
Full stack: 
*************************
1505893714845	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483658"
1505893714845	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483660"
1505893716757	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.linkedin.com/nhome/?trk="

Thank you

J

**Comment by 0x09AL** [comment]
Can you share the exact Firefox Version ?
Also this tool is not proxy aware so keep that in mind.

**Comment by jimmybarber** [comment]
Hi, 

Current Firefox version is 55.0.3 (64-bit)

Thank you
