### ISSUE TITLE
Disclosure of script in blog (Brazilian Portuguese)

### ISSUE THREAD

**Issue by tiagoxpl** [0x09AL/raven#17]
First of all, congratulations to the script and to spread it in the community. It's fantastic!

I created a [post](https://tiagosouza.com/raven-linkedin-information-gathering-tool/), in Portuguese from Brazil, in my blog about your script (Raven). My intention is to spread knowledge and present to the Brazilian public its excellent tool. If at any time you can reference my post, I will be very happy!

When you have news on new tools and scripts, let me know!

Best regards,

**Comment by 0x09AL** [comment]
Hi,
Thanks for letting me know but please don't open issues when there isn't one.

**Comment by 0x09AL** [comment]
Hi,
Thanks for letting me know but please don't open issues when there isn't one.
