### ISSUE TITLE
Get the following error, I have ensured selenium is installed

### ISSUE THREAD

**Issue by ghost** [0x09AL/raven#21]
[+] Saving output to output/test.com.csv 
Traceback (most recent call last):
  File "raven.py", line 180, in <module>
    RequesterObject.kill()
  File "/opt/raven/modules/requester.py", line 77, in kill
    self.driver.quit()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 199, in quit
    RemoteWebDriver.quit(self)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 691, in quit
    self.execute(Command.QUIT)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)

**Comment by mhedhliGVIT** [comment]
Same Issue

└──╼ $

> sudo python raven.py -c 'REDACTED' -s ny -d redacted.com
> 
> __________                                     _______       ________
> \______   \_____ ___  __ ____   ____           \   _  \      \_____  \
>  |       _/\__  \\  \/ // __ \ /    \   ______ /  /_\  \      /  ____/
>  |    |   \ / __ \\   /\  ___/|   |  \ /_____/ \  \_/   \    /       \
>  |____|_  /(____  /\_/  \___  >___|  /          \_____  / /\ \_______ \
>         \/      \/          \/     \/                 \/  \/         \/
>                                                                                LinkedIn Information Gathering Tool - by @0x09AL
> [+] Getting profiles from Google [+]
> [+] Parsing Data from html file [+]
> [+] Login Page loaded successfully [+]
> [+] Login Success [+]
> [+] Found a total of 0 profiles. [+]
> [+] Parsing all the profiles , this will take a while [+]
> [+] Profiles Parsed 0 [+]
> [+] Cleaning Invalid Data [+]
> [+] Mail functions initialized [+]
> ╒════════╤════════════╤═══════════╤══════════╕
> │ Name   │ Position   │ Company   │ E-mail   │
> ╞════════╪════════════╪═══════════╪══════════╡
> ╘════════╧════════════╧═══════════╧══════════╛
> [+] Saving output to output/redacted.com-1529344105.csv 
> Traceback (most recent call last):
>   File "raven.py", line 180, in <module>
>     RequesterObject.kill()
>   File "/opt/raven/modules/requester.py", line 77, in kill
>     self.driver.quit()
>   File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 187, in quit
>     RemoteWebDriver.quit(self)
>   File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 606, in quit
>     self.execute(Command.QUIT)
>   File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
>     self.error_handler.check_response(response)
>   File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: quit

**Comment by mhedhliGVIT** [comment]
Fixed traceback for me: https://github.com/0x09AL/raven/issues/11

> To fix this issue edit the file /usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py and change the self.execute(Command.QUIT) statement with the following:
> 
> self.execute(Command.CLOSE)
> 
> This fixed the error for me. Hope it can help
