### ISSUE TITLE
[-] Error : list index out of range [-]

### ISSUE THREAD

**Issue by DocKali** [0x09AL/raven#23]
First, thank you for this useful tool. I installed it without problem and it seems to work fine except the following error. For every LinkedIn profile the tool find, I have a message "[-] Error : list index out of range [-]
" and the profile is not parsed.

I saw in another post that the problem may be resolved by cleaning cache and cookies in Firefox. I did it, but this didn't solve my problem. Any ideas?

**Comment by 0x09AL** [comment]
Hi,
Thanks for opening an issue. I'm aware of this bug , it happens because linkedin changed its layout which broke the extraction.

I'm rewriting this tool in another language so you need to wait a little bit until i find some time :)

**Comment by DocKali** [comment]
Hi,
Thank you for this answer and for your work around this useful tool. Good luck for the rewriting, I will wait for the comit ;)
