### ISSUE TITLE
Parser.getCompany() fails

### ISSUE THREAD

**Issue by cclauss** [0x09AL/raven#5]
https://github.com/0x09AL/raven/blob/master/modules/parser.py#L22

https://github.com/0x09AL/raven/pull/4/files#diff-6bb4a0996d273f686c6c5a7ddc1f60f0R19

**Comment by 0x09AL** [comment]
Hello, thanks for reporting the issue but this function is still not implemented and never called in the code.
It will be implemented in a later version or when needed.
