### ISSUE TITLE
Linkedin search

### ISSUE THREAD

**Issue by redr2e** [0x09AL/raven#7]
Hey! As discussed here some hints to integrate the Linkedin search in Raven. Pop me a message if unclear:

first get company id: https://www.linkedin.com/ta/company?query=<company_name>
parse json response: resultList->id  (could be more than 1)

get list of employees: https://www.linkedin.com/search/results/people/?facetCurrentCompany=<companyId>&page=0
parse json within one of the "code" html tag, I use   if "VERTICAL" in <code[n]>:   to identify if I'm parsing the right json structure (there's more than 1)

Obviously you need to go through all the returned pages nad perform multiple requests to search/results/people/ with page incremented.

from here you can get firsName, lastName, occupation and few other info, without visiting the victim's profile (stealthy).

**Comment by 0x09AL** [comment]
Thanks will totally implement this one.

**Comment by 0x09AL** [comment]
I closed since this requires an account with a lot of connections.
Thanks for the suggestions
