### ISSUE TITLE
Feature Request - Pass linkedin username and password as parameters

### ISSUE THREAD

**Issue by Green-Wolf** [0x09AL/raven#8]
Hi, finally got the tool working on OSX, its really good!

I had a suggestion though, please could you make it so it's possible to provide the username and password as parameters from the command line so that we don't have to leave our password sitting in a file on disk or scrub it whenever we finish using raven?

**Comment by 0x09AL** [comment]
Hi, I'm glad you got it working.
Passing the username and password as a parameter really complicated the arguments that's why I decided to do this way.
I will rethink and if a lot of people ask for this i will do it.
Thanks

**Comment by pyperanger** [comment]
I make a quick recode for pass user and password as parameters
pull request
https://github.com/pyperanger/raven/blob/master/raven.py

**Comment by Green-Wolf** [comment]
Brilliant, thanks very much!

**Comment by 0x09AL** [comment]
Hi guys,
Just wanted to give a quick update. I added parameters as optional in this version.
Thanks

**Comment by Green-Wolf** [comment]
Fantastic, thanks for this!
